services:
  - type: web
    name: VyapaarAI
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        fromService:
          name: VyapaarAi-backend
          type: web
          property: url

  - type: web
    name: VyapaarAi-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
